Repository openwallet-foundation-labs/sd-jwt-js, pull requests merged in 2023-12, with the labels that each got.

#8 Add initial version of sd-jwt-js
  .gitignore
  .prettierrc
  NOTE
  README.md
  examples/README.md
  examples/all.ts
  examples/custom.ts
  examples/decoy.ts
  examples/issue.ts
  examples/package.json
  examples/pnpm-lock.yaml
  examples/present.ts
  examples/tsconfig.json
  examples/validate.ts
  examples/verify.ts
  jest.config.js
  package.json
  pnpm-lock.yaml
  src/base64url.ts
  src/crypto.ts
  src/decoy.ts
  src/disclosure.ts
  src/error.ts
  src/index.ts
  src/jwt.ts
  src/kbjwt.ts
  src/sdjwt.ts
  src/test/base64url.spec.ts
  src/test/crypto.spec.ts
  src/test/decoy.spec.ts
  src/test/disclosure.spec.ts
  src/test/jwt.spec.ts
  src/test/kbjwt.spec.ts
  src/test/pass.spec.ts
  src/test/sdjwt.spec.ts
  src/type.ts
  test/app-e2e.spec.ts
  test/array_data_types.json
  test/array_full_sd.json
  test/array_in_sd.json
  test/array_nested_in_plain.json
  test/array_none_disclosed.json
  test/array_of_nulls.json
  test/array_of_objects.json
  test/array_of_scalars.json
  test/array_recursive_sd.json
  test/array_recursive_sd_some_disclosed.json
  test/complex.json
  test/header_mod.json
  test/json_serialization.json
  test/key_binding.json
  test/no_sd.json
  test/object_data_types.json
  test/recursions.json
  tsconfig.json
Labels: enhancement

#10 Add license in package.json
  README.md
  package.json
Labels: bug, documentation

#12 [#11]Add security.md
  SECURITY.md
Labels: documentation

#14 [#13]Fix typo in README
  README.md
Labels: bug

#19 [#18]Add PR testing script
  .github/workflows/test-pr.yaml
Labels: enhancement

#15 Increase test coverage
  src/test/crypto.spec.ts
  src/test/disclosure.spec.ts
  src/test/error.spec.ts
  src/test/index.spec.ts
  src/test/jwt.spec.ts
  src/test/kbjwt.spec.ts
Labels: documentation

#22 [#21]Add measuring test coverage
  .gitignore
  README.md
  package.json
Labels: enhancement

#23 [#21]Fix badge URL
  README.md
Labels: bug

#24 Fix browser support
  package.json
  src/crypto-browser.ts
  src/crypto.ts
  src/jwt.ts
  src/type.ts
Labels: bug

#25 Rename zhzlabs to hopae
  README.md
  package.json
Labels: documentation

#27 [#26]Provide custom header in issue API
  examples/custom_header.ts
  examples/package.json
  src/index.ts
  src/type.ts
Labels: enhancement

#36 [#35]Add keybinding when present
  src/sdjwt.ts
Labels: bug

#29 [#28]Add github link to npm
  package.json
Labels: documentation

#31 [#30]Add key binding example
  examples/kb.ts
  examples/package.json
Labels: documentation

#33 [#32]Add more badges in README
  README.md
Labels: documentation

#41 Release: v1.1.0
  package.json
Labels: release

#42 Fix readme
  README.md
Labels: documentation
