Repository openwallet-foundation-labs/sd-jwt-js, pull requests merged in 2024-02, with the labels that each got.

#46 Support 07 version of standard and new features for v2.0
  README.md
  examples/kb.ts
  src/index.ts
  src/jwt.ts
  src/kbjwt.ts
  src/test/index.spec.ts
  src/test/jwt.spec.ts
  src/test/kbjwt.spec.ts
  src/type.ts
  test/app-e2e.spec.ts
Labels: enhancement

#50 [#49]fix: generate key binding jwt in present
  examples/kb.ts
  src/index.ts
  src/test/index.spec.ts
  src/type.ts
Labels: bug

#51 release: version 2.0
  package.json
Labels: documentation

#55 Add unit tests for decodeJWT function to validate JWT decoding
  src/test/jwt.spec.ts
Labels: testing

#54 Fix: missing interface for custom signer and verifier
  examples/all.ts
  examples/basic.ts
  examples/custom.ts
  examples/custom_header.ts
  examples/decoy.ts
  examples/kb.ts
  examples/sdjwtobject.ts
  package.json
  src/index.ts
  src/test/index.spec.ts
  src/type.ts
  test/app-e2e.spec.ts
Labels: bug

#61 doc: Fix typo in README
  README.md
Labels: documentation

#62 feat: use tsup as a bundler
  .github/workflows/test-pr.yaml
  package.json
  pnpm-lock.yaml
  src/test/base64url.spec.ts
  src/test/crypto.spec.ts
  src/test/decoy.spec.ts
  src/test/disclosure.spec.ts
  src/test/error.spec.ts
  src/test/index.spec.ts
  src/test/jwt.spec.ts
  src/test/kbjwt.spec.ts
  src/test/pass.spec.ts
  src/test/sdjwt.spec.ts
  test/app-e2e.spec.ts
  vitest.config.mts
Labels: testing

#63 Set up intro page in js.org
  .github/workflows/static.yml
  docs/index.html
Labels: documentation

#64 Add CNAME
  CNAME
Labels: documentation

#72 Add sync functions for decode/present
  packages/decode/src/decode.ts
  packages/decode/src/test/decode.spec.ts
  packages/node-crypto/src/crypto.ts
  packages/present/src/present.ts
  packages/present/src/test/present.spec.ts
  packages/types/src/type.ts
  packages/utils/src/disclosure.ts
Labels: enhancement

#73 Add 0.x markdown documentation
  docs/0.x/README.md
  docs/0.x/claims.md
  docs/0.x/disclosureframe.md
  docs/0.x/encode-decode.md
  docs/0.x/issue.md
  docs/0.x/keybinding.md
  docs/0.x/present.md
  docs/0.x/sdjwt-instance.md
  docs/0.x/validate.md
  docs/0.x/verify.md
  docs/README.md
  docs/imgs/concept.png
  docs/index.html
  docs/sdjwt.html
Labels: documentation

#106 feat: es crypto features to nodejs and browser
  packages/browser-crypto/src/crypto.ts
  packages/browser-crypto/src/test/crypto.spec.ts
  packages/node-crypto/src/crypto.ts
  packages/node-crypto/src/test/crypto.spec.ts
Labels: feature
